name: CI

on: [
    'pull_request'
]

jobs:
    tests:
        runs-on: ubuntu-latest
        matrix:
            php-version: ['7.3', '7.4', '8.0']

        steps:
            - name: Checkout
              uses: actions/checkout@v1
              with:
                  fetch-depth: 1

            - name: Composer get cache directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Composer cache
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Composer install
              run: |
                  composer --version
                  composer install --optimize-autoloader

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, intl

            - name: Codecept run
              run: composer test

    checks:
        runs-on: ubuntu-latest
        matrix:
            php-version: ['7.3', '8.0']

        steps:
            - name: Checkout
              uses: actions/checkout@v1
              with:
                  fetch-depth: 1

            - name: Composer validate
              run: composer validate

            - name: Composer get cache directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Composer cache
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Composer install
              run: |
                  composer --version
                  composer install --optimize-autoloader

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, intl

            - name: CodeStyle checks
              run: composer cs-check

            - name: PHPStan checks
              run: composer stan


